// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtelRezervasyonAPI.Context;

#nullable disable

namespace OtelRezervasyonAPI.Migrations
{
    [DbContext(typeof(OtelRezervasyonContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtelRezervasyonAPI.Entities.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdaNo")
                        .HasColumnType("int");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteris");
                });

            modelBuilder.Entity("OtelRezervasyonAPI.Entities.Oda", b =>
                {
                    b.Property<int>("OdaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdaId"));

                    b.Property<bool>("Doluluk")
                        .HasColumnType("bit");

                    b.Property<int>("OdaNo")
                        .HasColumnType("int");

                    b.Property<string>("OdaTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdaId");

                    b.ToTable("Odas");
                });

            modelBuilder.Entity("OtelRezervasyonAPI.Entities.Otel", b =>
                {
                    b.Property<int>("OtelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtelId"));

                    b.Property<int>("OdaSayısı")
                        .HasColumnType("int");

                    b.Property<string>("OtelAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OtelId");

                    b.ToTable("Otels");
                });

            modelBuilder.Entity("OtelRezervasyonAPI.Entities.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonId"));

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RezervasyonId");

                    b.ToTable("Rezervasyons");
                });
#pragma warning restore 612, 618
        }
    }
}
